---
- name: "update apt"
  become: yes
  apt:
    update_cache: yes
- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "install dependencies."
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes
- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
  environment:
    ENVIRONMENT=production
    NODE_ENV=production
    TYPEORM_CONNECTION=postgres
    TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts
    TYPEORM_HOST="${TYPEORM_HOST}"
    TYPEORM_PORT="${TYPEORM_PORT}"
    TYPEORM_USERNAME="${TYPEORM_USERNAME}"
    TYPEORM_PASSWORD="${TYPEORM_PASSWORD}"
    TYPEORM_DATABASE="${TYPEORM_DATABASE}"


