- name: Create directory
  file:
    path: /home/ubuntu/backend
    state: directory

- name: Copy backend files to home server
  copy:
    src: /root/project/backend
    dest: /home/ubuntu/
- name: Install Node 
  shell: |
    cd /home/ubuntu/backend
    npm install

- name: Build package
  shell: |
    cd /home/ubuntu/backend
    
    printenv |grep TYPEORM >.env
    echo ENVIRONMENT=production >>.env
    echo NODE_ENV=production >>.env
    echo "$(cat .env)"

    npm i
    sudo npm install -g typescript
    npm run build
    npm prune --production
    npm run start:prod
    #npm run prestart:prod
- name: Start PM2
  shell: |
    cd /home/ubuntu/backend
    pm2 start npm --name backend -- start
- name: start pm2 for dist/main.js
  become: no
  shell: |
    pm2 start main.js
    sudo env PATH=$PATH:/usr/bin /usr/local/lib/node_modules/pm2/bin/pm2 startup systemd -u ubuntu --hp /home/ubuntu
  args:
    chdir: /home/ubuntu/backend/dist
