- name: Create directory
  file:
    path: /home/ubuntu/backend
    state: directory

- name: Copy backend files to home server
  copy:
    src: /root/project/backend
    dest: /home/ubuntu/
- name: Install Node 
  shell: |
    cd /home/ubuntu/backend
    npm install

- name: Build package
  shell: |
    cd /home/ubuntu/backend
    
    printenv |grep TYPEORM >.env
    echo ENVIRONMENT=production >>.env
    echo NODE_ENV=production >>.env
    echo "$(cat .env)"
    npm i
    
    npm run build
    npm run prestart:prod
- name: Start PM2
  shell: |
    cd /home/ubuntu/backend
    pm2 start npm --name backend -- start
- name: start pm2 for dist/main.js
  become: no
  shell: pm2 start main.js
  args:
    chdir: /home/ubuntu/backend/dist
